// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCffDwrQBiR0YrCEiTjOvDT1y8opuHeEkk',
    appId: '1:896491386071:android:adea2a16b12dfdf6fd6c92',
    messagingSenderId: '896491386071',
    projectId: 'aurachat-c08fd',
    storageBucket: 'aurachat-c08fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRqaDgZCOLP4W0tdU9IF122nYHFGXlL7U',
    appId: '1:896491386071:ios:e48c7c1543dad475fd6c92',
    messagingSenderId: '896491386071',
    projectId: 'aurachat-c08fd',
    storageBucket: 'aurachat-c08fd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRqaDgZCOLP4W0tdU9IF122nYHFGXlL7U',
    appId: '1:896491386071:ios:e48c7c1543dad475fd6c92',
    messagingSenderId: '896491386071',
    projectId: 'aurachat-c08fd',
    storageBucket: 'aurachat-c08fd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
